services:
  app:
    image: mysociety/uk-parl-written-questions:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/uk_parl_written_questions      
    volumes:
      - ./:/workspaces/uk_parl_written_questions/